name: Test des Secrets

on: [workflow_dispatch]

jobs:
  print-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Tenter de lire le secret
        # On passe le secret dans une variable d'environnement (env)
        env:
          LE_MOT_DE_PASSE: ${{ secrets.MY_SUPER_PASSWORD }}
        run: |
          echo "Testons l'affichage du mot de passe :"
          echo "Le mot de passe est : $LE_MOT_DE_PASSE"